import type { InvoiceTemplateSettings } from '../types';

export const DEFAULT_INVOICE_TEMPLATE: InvoiceTemplateSettings = {
  headerTitle: '',
  subTitle: '',
  ownerPhone: '',
  locationAddress: '',
  footerNotes: '',
  paperSize: 'thermal_58',

  showLogo: true,
  showSystemBrand: true,
  showGeneratorName: true,
  showSubTitle: false,
  showDate: true,
  showReceiptNumber: true,
  showSubscriberName: true,
  showPhone: true,
  showOwnerPhone: false,
  showLocationAddress: false,
  showLineName: true,
  showAmperes: true,
  showPricePerAmp: true,
  showPaymentMonth: true,
  showPaymentStatus: true,
  showCollectorName: true,
  showPreviousDebt: true,
  showCurrentCharge: true,
  showTotalBeforePayment: true,
  showAppliedToPreviousDebt: false,
  showAppliedToCurrentMonth: true,
  showRemainingAfterPayment: true,
  showReceivedAmount: true,
  showThankYou: true,
  showQr: true,
  showFooterNotes: true,
  showFooterSystemText: true,

  systemBrandText: 'مولدتك',
  dateLabel: 'التاريخ',
  receiptNumberLabel: 'رقم الوصل',
  subscriberNameLabel: 'اسم المشترك',
  phoneLabel: 'رقم الهاتف',
  ownerPhoneLabel: 'هاتف الإدارة',
  locationAddressLabel: 'العنوان',
  lineNameLabel: 'الكابينة',
  amperesLabel: 'عدد الأمبيرات',
  pricePerAmpLabel: 'سعر الأمبير الشهري',
  paymentMonthLabel: 'شهر التسديد',
  paymentStatusLabel: 'حالة التسديد',
  collectorNameLabel: 'المحاسب',
  previousDebtLabel: 'الدين السابق',
  currentChargeLabel: 'استحقاق الشهر الحالي',
  totalBeforePaymentLabel: 'الإجمالي قبل التسديد',
  appliedToPreviousDebtLabel: 'تسديد الدين السابق',
  appliedToCurrentMonthLabel: 'تسديد الشهر الحالي',
  remainingAfterPaymentLabel: 'المتبقي بعد التسديد',
  receivedAmountLabel: 'المبلغ المستلم',
  thankYouText: 'شكراً لتسديدكم',
  qrCaption: 'امسح الرمز لمتابعة حسابك',
  footerSystemText: 'نظام إدارة المولدات والجباية',
};

export function normalizeInvoiceTemplate(value?: Partial<InvoiceTemplateSettings> | null): InvoiceTemplateSettings {
  const raw = value || {};
  const legacy: any = raw;
  const paper = raw.paperSize === 'thermal' ? 'thermal_58' : raw.paperSize;
  return {
    ...DEFAULT_INVOICE_TEMPLATE,
    ...raw,
    paperSize: (paper || DEFAULT_INVOICE_TEMPLATE.paperSize) as InvoiceTemplateSettings['paperSize'],
    headerTitle: String(raw.headerTitle || legacy.generatorName || DEFAULT_INVOICE_TEMPLATE.headerTitle),
    footerNotes: String(raw.footerNotes ?? legacy.customNoteText ?? legacy.footerNote ?? ''),
    showGeneratorName: raw.showGeneratorName ?? legacy.showGeneratorName ?? true,
    showPhone: raw.showPhone ?? legacy.showPhoneOnReceipt ?? true,
    showLineName: raw.showLineName ?? legacy.showPhaseName ?? true,
    showAmperes: raw.showAmperes ?? legacy.showAmperesCount ?? true,
    showPricePerAmp: raw.showPricePerAmp ?? legacy.showAmperesPrice ?? true,
    showPaymentMonth: raw.showPaymentMonth ?? legacy.showPaymentMonth ?? true,
    showCollectorName: raw.showCollectorName ?? legacy.showCollectorName ?? true,
    showPreviousDebt: raw.showPreviousDebt ?? legacy.showDueDebt ?? true,
    showReceivedAmount: raw.showReceivedAmount ?? legacy.showTotalAmount ?? true,
    showQr: raw.showQr ?? legacy.showBarcode ?? true,
  };
}

export type ReceiptVisibilityKey = Extract<keyof InvoiceTemplateSettings, `show${string}`>;
export type ReceiptTextKey = Extract<keyof InvoiceTemplateSettings, `${string}Label`> | 'systemBrandText' | 'thankYouText' | 'qrCaption' | 'footerSystemText';

export const receiptVisibilityFields: Array<{ key: ReceiptVisibilityKey; label: string }> = [
  { key: 'showLogo', label: 'شعار مولدتك' },
  { key: 'showSystemBrand', label: 'اسم النظام' },
  { key: 'showGeneratorName', label: 'اسم المولدة' },
  { key: 'showSubTitle', label: 'العنوان الفرعي' },
  { key: 'showDate', label: 'التاريخ' },
  { key: 'showReceiptNumber', label: 'رقم الوصل' },
  { key: 'showSubscriberName', label: 'اسم المشترك' },
  { key: 'showPhone', label: 'رقم هاتف المشترك' },
  { key: 'showOwnerPhone', label: 'هاتف الإدارة' },
  { key: 'showLocationAddress', label: 'عنوان المولدة' },
  { key: 'showLineName', label: 'الكابينة / الخط' },
  { key: 'showAmperes', label: 'عدد الأمبيرات' },
  { key: 'showPricePerAmp', label: 'سعر الأمبير' },
  { key: 'showPaymentMonth', label: 'شهر التسديد' },
  { key: 'showPaymentStatus', label: 'حالة التسديد' },
  { key: 'showCollectorName', label: 'اسم المحاسب / الجابي' },
  { key: 'showPreviousDebt', label: 'الدين السابق' },
  { key: 'showCurrentCharge', label: 'استحقاق الشهر الحالي' },
  { key: 'showTotalBeforePayment', label: 'الإجمالي قبل التسديد' },
  { key: 'showAppliedToPreviousDebt', label: 'تسديد الدين السابق' },
  { key: 'showAppliedToCurrentMonth', label: 'تسديد الشهر الحالي' },
  { key: 'showRemainingAfterPayment', label: 'المتبقي بعد التسديد' },
  { key: 'showReceivedAmount', label: 'المبلغ المستلم' },
  { key: 'showThankYou', label: 'عبارة الشكر' },
  { key: 'showQr', label: 'رمز QR' },
  { key: 'showFooterNotes', label: 'الملاحظة المخصصة' },
  { key: 'showFooterSystemText', label: 'تذييل النظام' },
];

export const receiptLabelFields: Array<{ key: ReceiptTextKey; label: string }> = [
  { key: 'systemBrandText', label: 'اسم النظام' },
  { key: 'dateLabel', label: 'عنوان التاريخ' },
  { key: 'receiptNumberLabel', label: 'عنوان رقم الوصل' },
  { key: 'subscriberNameLabel', label: 'عنوان اسم المشترك' },
  { key: 'phoneLabel', label: 'عنوان رقم هاتف المشترك' },
  { key: 'ownerPhoneLabel', label: 'عنوان هاتف الإدارة' },
  { key: 'locationAddressLabel', label: 'عنوان موقع المولدة' },
  { key: 'lineNameLabel', label: 'عنوان الكابينة / الخط' },
  { key: 'amperesLabel', label: 'عنوان عدد الأمبيرات' },
  { key: 'pricePerAmpLabel', label: 'عنوان سعر الأمبير' },
  { key: 'paymentMonthLabel', label: 'عنوان شهر التسديد' },
  { key: 'paymentStatusLabel', label: 'عنوان حالة التسديد' },
  { key: 'collectorNameLabel', label: 'عنوان المحاسب / الجابي' },
  { key: 'previousDebtLabel', label: 'عنوان الدين السابق' },
  { key: 'currentChargeLabel', label: 'عنوان استحقاق الشهر' },
  { key: 'totalBeforePaymentLabel', label: 'عنوان الإجمالي قبل التسديد' },
  { key: 'appliedToPreviousDebtLabel', label: 'عنوان تسديد الدين السابق' },
  { key: 'appliedToCurrentMonthLabel', label: 'عنوان تسديد الشهر الحالي' },
  { key: 'remainingAfterPaymentLabel', label: 'عنوان المتبقي بعد التسديد' },
  { key: 'receivedAmountLabel', label: 'عنوان المبلغ المستلم' },
  { key: 'thankYouText', label: 'عبارة الشكر' },
  { key: 'qrCaption', label: 'النص أعلى QR' },
  { key: 'footerSystemText', label: 'نص تذييل النظام' },
];
