import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = path => readFileSync(path, 'utf8');
const app = source('src/App.tsx');
const main = source('src/main.tsx');
const receipt = source('src/components/InvoiceReceiptModal.tsx');
const portal = source('src/components/SubscriberPortalPage.tsx');
const portalMigration = source('supabase/migrations/20260919110000_subscriber_portal_qr.sql');
const sunmiPrinter = source('android/app/src/main/java/com/mwaldatk/app/SunmiPrinterPlugin.java');
const sync = source('src/lib/useEventDrivenGeneratorSync.ts');
const admin = source('src/components/SuperAdminDashboard.tsx');
const mobile = source('src/components/mobile/MobileDashboard.tsx');
const desktop = source('src/components/DashboardView.tsx');
const sw = source('public/sw.js');
const collectorPos = source('src/components/POSQuickView.tsx');
const mobileHeader = source('src/components/mobile/MobileHeader.tsx');
const mobileBottomNav = source('src/components/MobileBottomNav.tsx');
const css = source('src/index.css');
const mobileSubscribers = source('src/components/mobile/MobileSubscribers.tsx');
const folderDetail = source('src/components/FolderDetailModal.tsx');
const settingsFolder = source('src/components/SettingsFolderView.tsx');
const invoiceTemplateLib = source('src/lib/invoiceTemplate.ts');
const login = source('src/components/LoginView.tsx');
const authAccounts = source('src/lib/authAccounts.ts');
const authEdge = source('supabase/functions/moldatk-auth/index.ts');
const authMigration = source('supabase/migrations/20260920090000_saved_account_passkeys.sql');
const count = (text, marker) => text.split(marker).length - 1;

assert.match(app, /lazy\(\(\) => import\('\.\/components\/SuperAdminDashboard'\)/);
assert.match(app, /SUBSCRIPTION_ACCESS_RPC_V2/);
assert.match(app, /supabase\.rpc\('get_my_subscription_access_state'\)/);
assert.match(app, /serverAccessActive/);
assert.match(app, /SubscriptionUnavailableScreen/);
assert.doesNotMatch(app, /userSession\.role === 'generator_admin' && sub\.error/);
assert.match(main, /subscriberPortalMatch/);
assert.match(main, /SubscriberPortalPage/);
assert.match(receipt, /MOLDATK_SUBSCRIBER_PORTAL_QR_V1/);
assert.match(receipt, /generatorId=|generatorId\?:/);
assert.match(receipt, /qrDataUrl/);
assert.doesNotMatch(receipt, /receipt-portal-url/);
assert.match(portal, /get_public_subscriber_account/);
assert.doesNotMatch(portal, /subscriber\.phone|subscriber\.address|subscriber\.notes/);
assert.match(portalMigration, /subscriber_portal_tokens/);
assert.match(portalMigration, /revoke all on table public\.subscriber_portal_tokens from public, anon, authenticated/);
assert.match(portalMigration, /get_public_subscriber_account/);
assert.match(portalMigration, /grant execute on function public\.get_public_subscriber_account\(uuid\) to anon/);
assert.match(sunmiPrinter, /MOLDATK_NATIVE_SUBSCRIBER_QR_V2/);
assert.match(sunmiPrinter, /private Bitmap decodeQrDataUrl/);
assert.match(admin, /await import\('xlsx'\)/);
assert.doesNotMatch(admin, /import \* as XLSX from 'xlsx'/);
assert.match(sync, /const changedSubscriberIds = new Set<string>/);
assert.match(sync, /sent\.deletedSubscribers/);
assert.match(sync, /delete_generator_tariff_month/);
assert.match(sync, /reconcile_generator_no_tariff_state/);
assert.equal(count(mobile, '<section data-ampere-discount-dashboard-mobile-v1'), 1);
assert.equal(count(desktop, '<section data-ampere-discount-dashboard'), 1);
assert.doesNotMatch(sw, /client\.navigate\(client\.url\)/);
assert.match(sw, /url\.pathname\.startsWith\('\/assets\/'\)/);
console.log('Source guards passed.');

assert.match(css, /MOLDATK_IOS_PWA_SAFE_AREA_V1/);
assert.match(css, /safe-area-inset-top/);
assert.match(css, /safe-area-inset-bottom/);
assert.match(css, /100dvh/);
assert.match(collectorPos, /moldatk-safe-screen/);
assert.match(mobileHeader, /moldatk-mobile-header-safe/);
assert.match(mobileBottomNav, /moldatk-mobile-bottom-safe/);

assert.match(mobileSubscribers, /MOBILE_PAYMENT_STATUS_CLASSIFICATION_V2/);
assert.match(mobileSubscribers, /sub\.paymentStatus === 'paid'/);
assert.match(mobileSubscribers, /sub\.paymentStatus === 'partial'/);
assert.doesNotMatch(mobileSubscribers, /sub\.paymentStatus === 'paid' \|\| getRemainingAmount\(sub\) === 0/);
assert.match(mobileSubscribers, /مسدد جزئي/);

assert.match(app, /normalizeInvoiceTemplate/);
assert.match(app, /invoiceTemplate=\{invoiceTemplate\}/);
assert.match(app, /moldatk_invoice_template/);
assert.match(folderDetail, /receiptVisibilityFields/);
assert.match(folderDetail, /receiptLabelFields/);
assert.match(folderDetail, /إعدادات الوصل الفعلية/);
assert.match(settingsFolder, /onOpenFolderModal\('invoices_templates'\)/);
assert.match(receipt, /MOLDATK_RECEIPT_TEMPLATE_V2/);
assert.match(receipt, /template\.showFooterNotes/);
assert.match(receipt, /template\.showQr/);
assert.match(receipt, /template\.showReceiptNumber/);
assert.match(receipt, /template\.footerNotes/);
assert.match(invoiceTemplateLib, /normalizeInvoiceTemplate/);
assert.match(invoiceTemplateLib, /showAppliedToPreviousDebt/);
assert.match(sunmiPrinter, /MOLDATK_NATIVE_SUBSCRIBER_QR_V2/);
assert.match(sunmiPrinter, /showReceiptNumber/);
assert.match(sunmiPrinter, /showFooterNotes/);
assert.doesNotMatch(receipt, /receipt-portal-url/);


assert.match(login, /إضافة حساب آخر/);
assert.match(login, /loginWithPasskey/);
assert.match(login, /registerPasskeyForCurrentAccount/);
assert.match(login, /\/brand\/moldatk-mark\.svg/);
assert.match(authAccounts, /moldatk_saved_login_accounts_v2/);
assert.match(authAccounts, /navigator\.credentials\.create/);
assert.match(authAccounts, /navigator\.credentials\.get/);
assert.match(app, /QUICK_LOGIN_LOCK_V2/);
assert.match(app, /moldatk_session_unlocked_v2/);
assert.match(authEdge, /passkey-auth-verify/);
assert.match(authEdge, /password-login/);
assert.match(authMigration, /moldatk_passkeys/);
